FROM python:3.9-slim-buster

WORKDIR /app

COPY /fileupload-mapper/backend/requirements.txt requirements.txt

RUN python -m pip install --upgrade pip

RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY . ./

CMD [ "python", "main.py"]
